[package]
name = "oriac"
version = "0.0.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
num-bigint = "0.4.3"
serde = { version = "1.0.136", features = ["derive"] }
serde_with = "1.11.0"
thiserror = "1.0.30"

[dev-dependencies]
serde_json = "1.0.78"
